[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "snowflake-cli-labs"
author = "Snowflake, Inc"
license = "Apache-2.0"
license_files = ["LICENSE"]
dynamic = ["version"]
requires-python = ">=3.8"
description = "Snowflake CLI"
readme = "README.md"
dependencies = [
  "coverage==7.3.0",
  "jinja2==3.1.2",
  "rich==13.5.2",
  "requests==2.31.0",
  "requirements-parser==0.5.0",
  "snowflake-connector-python[secure-local-storage]==3.1.0",
  "tomlkit==0.12.1",
  "typer==0.9.0",
  "urllib3<1.27,>=1.21.1",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: System Administrators",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: SQL",
  "Topic :: Database"
]

[project.optional-dependencies]
dev = [
  "coverage==7.3.0",
  "pre-commit==3.3.3",
  "pytest==7.4.0",
  "syrupy==4.2.0",
  "tox==4.10.0",
]

[project.urls]
"Source code" = "https://github.com/Snowflake-Labs/snowcli"
"Bug Tracker" = "https://github.com/Snowflake-Labs/snowcli/issues"

[project.scripts]
snow = "snowcli.__main__:main"

[tool.hatch.version]
path = "src/snowcli/__about__.py"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
]

[tool.hatch.build.targets.wheel]
packages = ["src/snowcli", "src/templates"]

[tool.ruff]
line-length = 88
select = [
    # isort
    "I001"
]

[tool.pytest.ini_options]
addopts = "-m 'not integration'"
markers = [
  "integration: mark test as integration test",
]
